networks:
  bank-network:
    external: true  # If the network does not exist, it must be created manually first

volumes:
  original-database-volume:
    external: true  
  auth-database-volume:
    external: true  
  core-database-01-volume:
    external: true  
  core-database-02-volume:
    external: true  
  redis-volume:
    external: true  
  kafka-volume:
  manage-service-logs:
  auth-service-logs:
  transaction-service-logs:
  notification-service-logs:

  
services:
  original-database:
    container_name: original-database
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secret}
      - POSTGRES_DB=${PG_DATABASE_ORIGINAL_DB:-original_db}
    ports:
      - "${PG_PORT_ORIGINAL_DB}:5432"
    networks:
      - bank-network
    volumes:
      - original-database-volume:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${PG_USER:-postgres} -d ${PG_DATABASE_ORIGINAL_DB:-original_db} || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
  
  auth-database:
    container_name: auth-database
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secret}
      - POSTGRES_DB=${PG_DATABASE_AUTH_DB:-auth_db}
    ports:
      - "${PG_PORT_AUTH_DB}:5432"
    networks:
      - bank-network
    volumes:
      - auth-database-volume:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${PG_USER:-postgres} -d ${PG_DATABASE_AUTH_DB:-auth_db} || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  core-database-01:
    container_name: core-database-01
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secret}
      - POSTGRES_DB=${PG_DATABASE_CORE_DB:-core_db}
    ports:
      - "${PG_PORT_SHARD_1}:5432"
    networks:
      - bank-network
    volumes:
      - core-database-01-volume:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${PG_USER:-postgres} -d ${PG_DATABASE_CORE_DB:-core_db} || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  core-database-02:
    container_name: core-database-02
    image: postgres:17.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER:-postgres}
      - POSTGRES_PASSWORD=${PG_PASSWORD:-secret}
      - POSTGRES_DB=${PG_DATABASE_CORE_DB:-core_db}
    ports:
      - "${PG_PORT_SHARD_2}:5432"
    networks:
      - bank-network
    volumes:
      - core-database-02-volume:/var/lib/postgresql/data
    command: >
      postgres -c max_connections=200
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5432 -U ${PG_USER:-postgres} -d ${PG_DATABASE_CORE_DB:-core_db} || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

  redis:
    container_name: redis
    image: redis:7.4-alpine3.20
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - bank-network
    volumes:
      - redis-volume:/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2g

  # kafka:
  #   container_name: kafka
  #   image: bitnami/kafka:3.6.2
  #   restart: always
  #   ports:
  #   - "9092:9092"
  #   - "9093:9093"  # Expose the controller port
  #   environment:
  #     # KRaft settings
  #     - KAFKA_CFG_NODE_ID=1
  #     - KAFKA_CFG_PROCESS_ROLES=controller,broker
  #     - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
  #     # Listeners
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
  #     - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  #     - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
  #   networks:
  #     - bank-network
  #   volumes:
  #     - kafka-volume:/bitnami/kafka 
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1g

  # reverse-proxy:
  #   container_name: reverse-proxy
  #   image: nginx:1.27.2
  #   restart: unless-stopped
  #   volumes:
  #     - ./nginx/templates:/etc/nginx/templates
  #     - ./nginx/configuration/custom_proxy_settings.conf:/etc/nginx/conf.d/custom_proxy_settings.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - bank-network

  # auth-service:
  #   container_name: auth-service
  #   image: auth-service
  #   restart: unless-stopped
  #   depends_on:
  #     auth-database:
  #       condition: service_healthy
  #   networks:
  #     - bank-network

  # management-service:
  #   container_name: management-service
  #   image: management-service
  #   restart: unless-stopped
  #   depends_on:
  #     core-database-01:
  #       condition: service_healthy
  #     core-database-02:
  #       condition: service_healthy
  #   networks:
  #     - bank-network

  # transfermoney-service:
  #   container_name: transfermoney-service
  #   image: transfermoney-service
  #   restart: unless-stopped
  #   depends_on:
  #     core-database-01:
  #       condition: service_healthy
  #     core-database-02:
  #       condition: service_healthy
  #   networks:
  #     - bank-network