// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: management/account/rpc_get_account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByAccNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccNumber string `protobuf:"bytes,1,opt,name=acc_number,json=accNumber,proto3" json:"acc_number,omitempty"`
}

func (x *GetAccountByAccNumberRequest) Reset() {
	*x = GetAccountByAccNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_account_rpc_get_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByAccNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccNumberRequest) ProtoMessage() {}

func (x *GetAccountByAccNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_account_rpc_get_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccNumberRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByAccNumberRequest) Descriptor() ([]byte, []int) {
	return file_management_account_rpc_get_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByAccNumberRequest) GetAccNumber() string {
	if x != nil {
		return x.AccNumber
	}
	return ""
}

type GetAccountByAccNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetAccountByAccNumberResponse) Reset() {
	*x = GetAccountByAccNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_account_rpc_get_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByAccNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByAccNumberResponse) ProtoMessage() {}

func (x *GetAccountByAccNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_account_rpc_get_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByAccNumberResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByAccNumberResponse) Descriptor() ([]byte, []int) {
	return file_management_account_rpc_get_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByAccNumberResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type IGetAccountByAccNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccNumber string `protobuf:"bytes,1,opt,name=acc_number,json=accNumber,proto3" json:"acc_number,omitempty"`
}

func (x *IGetAccountByAccNumberRequest) Reset() {
	*x = IGetAccountByAccNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_account_rpc_get_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IGetAccountByAccNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IGetAccountByAccNumberRequest) ProtoMessage() {}

func (x *IGetAccountByAccNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_account_rpc_get_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IGetAccountByAccNumberRequest.ProtoReflect.Descriptor instead.
func (*IGetAccountByAccNumberRequest) Descriptor() ([]byte, []int) {
	return file_management_account_rpc_get_account_proto_rawDescGZIP(), []int{2}
}

func (x *IGetAccountByAccNumberRequest) GetAccNumber() string {
	if x != nil {
		return x.AccNumber
	}
	return ""
}

type IGetAccountByAccNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *IAccount `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *IGetAccountByAccNumberResponse) Reset() {
	*x = IGetAccountByAccNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_management_account_rpc_get_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IGetAccountByAccNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IGetAccountByAccNumberResponse) ProtoMessage() {}

func (x *IGetAccountByAccNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_account_rpc_get_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IGetAccountByAccNumberResponse.ProtoReflect.Descriptor instead.
func (*IGetAccountByAccNumberResponse) Descriptor() ([]byte, []int) {
	return file_management_account_rpc_get_account_proto_rawDescGZIP(), []int{3}
}

func (x *IGetAccountByAccNumberResponse) GetAccount() *IAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_management_account_rpc_get_account_proto protoreflect.FileDescriptor

var file_management_account_rpc_get_account_proto_rawDesc = []byte{
	0x0a, 0x28, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x1a, 0x20, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x79, 0x41, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x3e, 0x0a, 0x1d, 0x49, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x79, 0x41, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x4d, 0x0a, 0x1e, 0x49, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x79, 0x41, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x49,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x75, 0x6e, 0x76, 0x78, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_management_account_rpc_get_account_proto_rawDescOnce sync.Once
	file_management_account_rpc_get_account_proto_rawDescData = file_management_account_rpc_get_account_proto_rawDesc
)

func file_management_account_rpc_get_account_proto_rawDescGZIP() []byte {
	file_management_account_rpc_get_account_proto_rawDescOnce.Do(func() {
		file_management_account_rpc_get_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_management_account_rpc_get_account_proto_rawDescData)
	})
	return file_management_account_rpc_get_account_proto_rawDescData
}

var file_management_account_rpc_get_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_management_account_rpc_get_account_proto_goTypes = []any{
	(*GetAccountByAccNumberRequest)(nil),   // 0: account.GetAccountByAccNumberRequest
	(*GetAccountByAccNumberResponse)(nil),  // 1: account.GetAccountByAccNumberResponse
	(*IGetAccountByAccNumberRequest)(nil),  // 2: account.IGetAccountByAccNumberRequest
	(*IGetAccountByAccNumberResponse)(nil), // 3: account.IGetAccountByAccNumberResponse
	(*Account)(nil),                        // 4: account.Account
	(*IAccount)(nil),                       // 5: account.IAccount
}
var file_management_account_rpc_get_account_proto_depIdxs = []int32{
	4, // 0: account.GetAccountByAccNumberResponse.account:type_name -> account.Account
	5, // 1: account.IGetAccountByAccNumberResponse.account:type_name -> account.IAccount
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_management_account_rpc_get_account_proto_init() }
func file_management_account_rpc_get_account_proto_init() {
	if File_management_account_rpc_get_account_proto != nil {
		return
	}
	file_management_account_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_management_account_rpc_get_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountByAccNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_account_rpc_get_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountByAccNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_account_rpc_get_account_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*IGetAccountByAccNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_management_account_rpc_get_account_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*IGetAccountByAccNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_management_account_rpc_get_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_account_rpc_get_account_proto_goTypes,
		DependencyIndexes: file_management_account_rpc_get_account_proto_depIdxs,
		MessageInfos:      file_management_account_rpc_get_account_proto_msgTypes,
	}.Build()
	File_management_account_rpc_get_account_proto = out.File
	file_management_account_rpc_get_account_proto_rawDesc = nil
	file_management_account_rpc_get_account_proto_goTypes = nil
	file_management_account_rpc_get_account_proto_depIdxs = nil
}
