// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: cusman/account/rpc_get_account.proto

package account

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *GetAccountByIDRequest) Reset() {
	*x = GetAccountByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cusman_account_rpc_get_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDRequest) ProtoMessage() {}

func (x *GetAccountByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cusman_account_rpc_get_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIDRequest) Descriptor() ([]byte, []int) {
	return file_cusman_account_rpc_get_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByIDRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetAccountByIDResponse) Reset() {
	*x = GetAccountByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cusman_account_rpc_get_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDResponse) ProtoMessage() {}

func (x *GetAccountByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cusman_account_rpc_get_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDResponse.ProtoReflect.Descriptor instead.
func (*GetAccountByIDResponse) Descriptor() ([]byte, []int) {
	return file_cusman_account_rpc_get_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByIDResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_cusman_account_rpc_get_account_proto protoreflect.FileDescriptor

var file_cusman_account_rpc_get_account_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x75, 0x73, 0x6d, 0x61, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x1a,
	0x1c, 0x63, 0x75, 0x73, 0x6d, 0x61, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2a, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x34, 0x5a, 0x32, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x6e, 0x76, 0x78, 0x2f,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x63, 0x75, 0x73, 0x6d, 0x61, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cusman_account_rpc_get_account_proto_rawDescOnce sync.Once
	file_cusman_account_rpc_get_account_proto_rawDescData = file_cusman_account_rpc_get_account_proto_rawDesc
)

func file_cusman_account_rpc_get_account_proto_rawDescGZIP() []byte {
	file_cusman_account_rpc_get_account_proto_rawDescOnce.Do(func() {
		file_cusman_account_rpc_get_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_cusman_account_rpc_get_account_proto_rawDescData)
	})
	return file_cusman_account_rpc_get_account_proto_rawDescData
}

var file_cusman_account_rpc_get_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cusman_account_rpc_get_account_proto_goTypes = []any{
	(*GetAccountByIDRequest)(nil),  // 0: account.GetAccountByIDRequest
	(*GetAccountByIDResponse)(nil), // 1: account.GetAccountByIDResponse
	(*Account)(nil),                // 2: account.Account
}
var file_cusman_account_rpc_get_account_proto_depIdxs = []int32{
	2, // 0: account.GetAccountByIDResponse.account:type_name -> account.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cusman_account_rpc_get_account_proto_init() }
func file_cusman_account_rpc_get_account_proto_init() {
	if File_cusman_account_rpc_get_account_proto != nil {
		return
	}
	file_cusman_account_account_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_cusman_account_rpc_get_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cusman_account_rpc_get_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cusman_account_rpc_get_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cusman_account_rpc_get_account_proto_goTypes,
		DependencyIndexes: file_cusman_account_rpc_get_account_proto_depIdxs,
		MessageInfos:      file_cusman_account_rpc_get_account_proto_msgTypes,
	}.Build()
	File_cusman_account_rpc_get_account_proto = out.File
	file_cusman_account_rpc_get_account_proto_rawDesc = nil
	file_cusman_account_rpc_get_account_proto_goTypes = nil
	file_cusman_account_rpc_get_account_proto_depIdxs = nil
}
