// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account_shard_map.sql

package db

import (
	"context"
)

const getShardByAccountID = `-- name: GetShardByAccountID :one
SELECT account_id, customer_id, shard_id FROM account_shard_map
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetShardByAccountID(ctx context.Context, accountID int64) (AccountShardMap, error) {
	row := q.db.QueryRow(ctx, getShardByAccountID, accountID)
	var i AccountShardMap
	err := row.Scan(&i.AccountID, &i.CustomerID, &i.ShardID)
	return i, err
}

const insertAccountShardMap = `-- name: InsertAccountShardMap :one
INSERT INTO account_shard_map (
  account_id,
  customer_id,
  shard_id
) VALUES (
  $1, $2, $3
) RETURNING account_id, customer_id, shard_id
`

type InsertAccountShardMapParams struct {
	AccountID  int64 `json:"account_id"`
	CustomerID int64 `json:"customer_id"`
	ShardID    int32 `json:"shard_id"`
}

func (q *Queries) InsertAccountShardMap(ctx context.Context, arg InsertAccountShardMapParams) (AccountShardMap, error) {
	row := q.db.QueryRow(ctx, insertAccountShardMap, arg.AccountID, arg.CustomerID, arg.ShardID)
	var i AccountShardMap
	err := row.Scan(&i.AccountID, &i.CustomerID, &i.ShardID)
	return i, err
}
