// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type AccountShardMap struct {
	AccountID  int64 `json:"account_id"`
	CustomerID int64 `json:"customer_id"`
}

type CustomerShardMap struct {
	CustomerID  int64  `json:"customer_id"`
	CustomerRid string `json:"customer_rid"`
	ShardID     int32  `json:"shard_id"`
}
