// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetShardByAccountID(ctx context.Context, accountID int64) (AccountShardMap, error)
	GetShardByCustomeRid(ctx context.Context, customerRid string) (CustomerShardMap, error)
	InsertAccountShardMap(ctx context.Context, arg InsertAccountShardMapParams) (AccountShardMap, error)
	InsertCustomerShardMap(ctx context.Context, arg InsertCustomerShardMapParams) (CustomerShardMap, error)
}

var _ Querier = (*Queries)(nil)
