// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: account.sql

package db

import (
	"context"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE accounts
SET current_balance = current_balance + $1
WHERE account_id = $2
RETURNING account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status
`

type AddAccountBalanceParams struct {
	Amount    int64 `json:"amount"`
	AccountID int64 `json:"account_id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.Amount, arg.AccountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.CurrentBalance,
		&i.CurrencyType,
		&i.CreatedAt,
		&i.Description,
		&i.AccountStatus,
	)
	return i, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    account_number,
    customer_id,
    current_balance,
    currency_type,
    account_status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status
`

type CreateAccountParams struct {
	AccountNumber  string        `json:"account_number"`
	CustomerID     int64         `json:"customer_id"`
	CurrentBalance int64         `json:"current_balance"`
	CurrencyType   Currencytype  `json:"currency_type"`
	AccountStatus  Accountstatus `json:"account_status"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.AccountNumber,
		arg.CustomerID,
		arg.CurrentBalance,
		arg.CurrencyType,
		arg.AccountStatus,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.CurrentBalance,
		&i.CurrencyType,
		&i.CreatedAt,
		&i.Description,
		&i.AccountStatus,
	)
	return i, err
}

const getAccountByAccNumber = `-- name: GetAccountByAccNumber :one
SELECT account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status FROM accounts
WHERE account_number = $1
LIMIT 1
`

func (q *Queries) GetAccountByAccNumber(ctx context.Context, accountNumber string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByAccNumber, accountNumber)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.CurrentBalance,
		&i.CurrencyType,
		&i.CreatedAt,
		&i.Description,
		&i.AccountStatus,
	)
	return i, err
}

const getAccountForUpdate = `-- name: GetAccountForUpdate :one

SELECT account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status FROM accounts
WHERE account_id = $1 LIMIT 1
FOR NO KEY UPDATE
`

// The methods below are directly related to transactions (multiple queries), so will be implemented query with id
// Especially directly related to the locking mechanism, locking in order in the database
// ...
func (q *Queries) GetAccountForUpdate(ctx context.Context, accountID int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, accountID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.CurrentBalance,
		&i.CurrencyType,
		&i.CreatedAt,
		&i.Description,
		&i.AccountStatus,
	)
	return i, err
}

const getAccountIDByAccNumber = `-- name: GetAccountIDByAccNumber :one
SELECT account_id FROM accounts
WHERE account_number = $1
LIMIT 1
`

func (q *Queries) GetAccountIDByAccNumber(ctx context.Context, accountNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountIDByAccNumber, accountNumber)
	var account_id int64
	err := row.Scan(&account_id)
	return account_id, err
}

const getCustomerIDByAccNumber = `-- name: GetCustomerIDByAccNumber :one
SELECT customer_id FROM accounts
WHERE account_number = $1
LIMIT 1
`

func (q *Queries) GetCustomerIDByAccNumber(ctx context.Context, accountNumber string) (int64, error) {
	row := q.db.QueryRow(ctx, getCustomerIDByAccNumber, accountNumber)
	var customer_id int64
	err := row.Scan(&customer_id)
	return customer_id, err
}

const listAccountByCustomerID = `-- name: ListAccountByCustomerID :many
SELECT account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status FROM accounts
WHERE 
    customer_id = $1 AND
    account_status = $2
ORDER BY account_id
LIMIT $3
OFFSET $4
`

type ListAccountByCustomerIDParams struct {
	CustomerID    int64         `json:"customer_id"`
	AccountStatus Accountstatus `json:"account_status"`
	Limit         int32         `json:"limit"`
	Offset        int32         `json:"offset"`
}

func (q *Queries) ListAccountByCustomerID(ctx context.Context, arg ListAccountByCustomerIDParams) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountByCustomerID,
		arg.CustomerID,
		arg.AccountStatus,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.AccountID,
			&i.AccountNumber,
			&i.CustomerID,
			&i.CurrentBalance,
			&i.CurrencyType,
			&i.CreatedAt,
			&i.Description,
			&i.AccountStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts 
SET current_balance = $2
WHERE account_id = $1
RETURNING account_id, account_number, customer_id, current_balance, currency_type, created_at, description, account_status
`

type UpdateAccountBalanceParams struct {
	AccountID      int64 `json:"account_id"`
	CurrentBalance int64 `json:"current_balance"`
}

func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.AccountID, arg.CurrentBalance)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.CustomerID,
		&i.CurrentBalance,
		&i.CurrencyType,
		&i.CreatedAt,
		&i.Description,
		&i.AccountStatus,
	)
	return i, err
}
