// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type CustomerCredential struct {
	CustomerID        int64     `json:"customer_id"`
	ShardID           int32     `json:"shard_id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	CreatedAt         time.Time `json:"created_at"`
	UsernameChangedAt time.Time `json:"username_changed_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
}

type CustomerSession struct {
	SessionID    uuid.UUID `json:"session_id"`
	CustomerID   int64     `json:"customer_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
