// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: shardman/rpc_insert_account_shard.proto

package shardman

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertAccountShardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  int64 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CustomerId int64 `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *InsertAccountShardRequest) Reset() {
	*x = InsertAccountShardRequest{}
	mi := &file_shardman_rpc_insert_account_shard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAccountShardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAccountShardRequest) ProtoMessage() {}

func (x *InsertAccountShardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shardman_rpc_insert_account_shard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAccountShardRequest.ProtoReflect.Descriptor instead.
func (*InsertAccountShardRequest) Descriptor() ([]byte, []int) {
	return file_shardman_rpc_insert_account_shard_proto_rawDescGZIP(), []int{0}
}

func (x *InsertAccountShardRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *InsertAccountShardRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type InsertAccountShardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsInserted bool `protobuf:"varint,1,opt,name=is_inserted,json=isInserted,proto3" json:"is_inserted,omitempty"`
}

func (x *InsertAccountShardResponse) Reset() {
	*x = InsertAccountShardResponse{}
	mi := &file_shardman_rpc_insert_account_shard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertAccountShardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertAccountShardResponse) ProtoMessage() {}

func (x *InsertAccountShardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shardman_rpc_insert_account_shard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertAccountShardResponse.ProtoReflect.Descriptor instead.
func (*InsertAccountShardResponse) Descriptor() ([]byte, []int) {
	return file_shardman_rpc_insert_account_shard_proto_rawDescGZIP(), []int{1}
}

func (x *InsertAccountShardResponse) GetIsInserted() bool {
	if x != nil {
		return x.IsInserted
	}
	return false
}

var File_shardman_rpc_insert_account_shard_proto protoreflect.FileDescriptor

var file_shardman_rpc_insert_account_shard_proto_rawDesc = []byte{
	0x0a, 0x27, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6d, 0x61, 0x6e, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x69,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x6d, 0x61, 0x6e, 0x22, 0x5b, 0x0a, 0x19, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x3d, 0x0a, 0x1a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x68, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x65, 0x64, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75,
	0x6e, 0x76, 0x78, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x64, 0x6d, 0x61, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shardman_rpc_insert_account_shard_proto_rawDescOnce sync.Once
	file_shardman_rpc_insert_account_shard_proto_rawDescData = file_shardman_rpc_insert_account_shard_proto_rawDesc
)

func file_shardman_rpc_insert_account_shard_proto_rawDescGZIP() []byte {
	file_shardman_rpc_insert_account_shard_proto_rawDescOnce.Do(func() {
		file_shardman_rpc_insert_account_shard_proto_rawDescData = protoimpl.X.CompressGZIP(file_shardman_rpc_insert_account_shard_proto_rawDescData)
	})
	return file_shardman_rpc_insert_account_shard_proto_rawDescData
}

var file_shardman_rpc_insert_account_shard_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shardman_rpc_insert_account_shard_proto_goTypes = []any{
	(*InsertAccountShardRequest)(nil),  // 0: shardman.InsertAccountShardRequest
	(*InsertAccountShardResponse)(nil), // 1: shardman.InsertAccountShardResponse
}
var file_shardman_rpc_insert_account_shard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shardman_rpc_insert_account_shard_proto_init() }
func file_shardman_rpc_insert_account_shard_proto_init() {
	if File_shardman_rpc_insert_account_shard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shardman_rpc_insert_account_shard_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shardman_rpc_insert_account_shard_proto_goTypes,
		DependencyIndexes: file_shardman_rpc_insert_account_shard_proto_depIdxs,
		MessageInfos:      file_shardman_rpc_insert_account_shard_proto_msgTypes,
	}.Build()
	File_shardman_rpc_insert_account_shard_proto = out.File
	file_shardman_rpc_insert_account_shard_proto_rawDesc = nil
	file_shardman_rpc_insert_account_shard_proto_goTypes = nil
	file_shardman_rpc_insert_account_shard_proto_depIdxs = nil
}
