// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: shardman/service_shardman.proto

package shardman

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShardManagementService_InsertAccountShard_FullMethodName     = "/shardman.ShardManagementService/InsertAccountShard"
	ShardManagementService_InsertCustomerShard_FullMethodName    = "/shardman.ShardManagementService/InsertCustomerShard"
	ShardManagementService_LookupAccountShardPair_FullMethodName = "/shardman.ShardManagementService/LookupAccountShardPair"
	ShardManagementService_LookupAccountShard_FullMethodName     = "/shardman.ShardManagementService/LookupAccountShard"
	ShardManagementService_LookupCustomerShard_FullMethodName    = "/shardman.ShardManagementService/LookupCustomerShard"
)

// ShardManagementServiceClient is the client API for ShardManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShardManagementServiceClient interface {
	InsertAccountShard(ctx context.Context, in *InsertAccountShardRequest, opts ...grpc.CallOption) (*InsertAccountShardResponse, error)
	InsertCustomerShard(ctx context.Context, in *InsertCustomerShardRequest, opts ...grpc.CallOption) (*InsertCustomerShardResponse, error)
	LookupAccountShardPair(ctx context.Context, in *LookupAccountShardPairRequest, opts ...grpc.CallOption) (*LookupAccountShardPairResponse, error)
	LookupAccountShard(ctx context.Context, in *LookupAccountShardRequest, opts ...grpc.CallOption) (*LookupAccountShardResponse, error)
	LookupCustomerShard(ctx context.Context, in *LookupCustomerShardRequest, opts ...grpc.CallOption) (*LookupCustomerShardResponse, error)
}

type shardManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShardManagementServiceClient(cc grpc.ClientConnInterface) ShardManagementServiceClient {
	return &shardManagementServiceClient{cc}
}

func (c *shardManagementServiceClient) InsertAccountShard(ctx context.Context, in *InsertAccountShardRequest, opts ...grpc.CallOption) (*InsertAccountShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertAccountShardResponse)
	err := c.cc.Invoke(ctx, ShardManagementService_InsertAccountShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardManagementServiceClient) InsertCustomerShard(ctx context.Context, in *InsertCustomerShardRequest, opts ...grpc.CallOption) (*InsertCustomerShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertCustomerShardResponse)
	err := c.cc.Invoke(ctx, ShardManagementService_InsertCustomerShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardManagementServiceClient) LookupAccountShardPair(ctx context.Context, in *LookupAccountShardPairRequest, opts ...grpc.CallOption) (*LookupAccountShardPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupAccountShardPairResponse)
	err := c.cc.Invoke(ctx, ShardManagementService_LookupAccountShardPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardManagementServiceClient) LookupAccountShard(ctx context.Context, in *LookupAccountShardRequest, opts ...grpc.CallOption) (*LookupAccountShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupAccountShardResponse)
	err := c.cc.Invoke(ctx, ShardManagementService_LookupAccountShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shardManagementServiceClient) LookupCustomerShard(ctx context.Context, in *LookupCustomerShardRequest, opts ...grpc.CallOption) (*LookupCustomerShardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupCustomerShardResponse)
	err := c.cc.Invoke(ctx, ShardManagementService_LookupCustomerShard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShardManagementServiceServer is the server API for ShardManagementService service.
// All implementations must embed UnimplementedShardManagementServiceServer
// for forward compatibility.
type ShardManagementServiceServer interface {
	InsertAccountShard(context.Context, *InsertAccountShardRequest) (*InsertAccountShardResponse, error)
	InsertCustomerShard(context.Context, *InsertCustomerShardRequest) (*InsertCustomerShardResponse, error)
	LookupAccountShardPair(context.Context, *LookupAccountShardPairRequest) (*LookupAccountShardPairResponse, error)
	LookupAccountShard(context.Context, *LookupAccountShardRequest) (*LookupAccountShardResponse, error)
	LookupCustomerShard(context.Context, *LookupCustomerShardRequest) (*LookupCustomerShardResponse, error)
	mustEmbedUnimplementedShardManagementServiceServer()
}

// UnimplementedShardManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShardManagementServiceServer struct{}

func (UnimplementedShardManagementServiceServer) InsertAccountShard(context.Context, *InsertAccountShardRequest) (*InsertAccountShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAccountShard not implemented")
}
func (UnimplementedShardManagementServiceServer) InsertCustomerShard(context.Context, *InsertCustomerShardRequest) (*InsertCustomerShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertCustomerShard not implemented")
}
func (UnimplementedShardManagementServiceServer) LookupAccountShardPair(context.Context, *LookupAccountShardPairRequest) (*LookupAccountShardPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupAccountShardPair not implemented")
}
func (UnimplementedShardManagementServiceServer) LookupAccountShard(context.Context, *LookupAccountShardRequest) (*LookupAccountShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupAccountShard not implemented")
}
func (UnimplementedShardManagementServiceServer) LookupCustomerShard(context.Context, *LookupCustomerShardRequest) (*LookupCustomerShardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupCustomerShard not implemented")
}
func (UnimplementedShardManagementServiceServer) mustEmbedUnimplementedShardManagementServiceServer() {
}
func (UnimplementedShardManagementServiceServer) testEmbeddedByValue() {}

// UnsafeShardManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShardManagementServiceServer will
// result in compilation errors.
type UnsafeShardManagementServiceServer interface {
	mustEmbedUnimplementedShardManagementServiceServer()
}

func RegisterShardManagementServiceServer(s grpc.ServiceRegistrar, srv ShardManagementServiceServer) {
	// If the following call pancis, it indicates UnimplementedShardManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShardManagementService_ServiceDesc, srv)
}

func _ShardManagementService_InsertAccountShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAccountShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardManagementServiceServer).InsertAccountShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardManagementService_InsertAccountShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardManagementServiceServer).InsertAccountShard(ctx, req.(*InsertAccountShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardManagementService_InsertCustomerShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertCustomerShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardManagementServiceServer).InsertCustomerShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardManagementService_InsertCustomerShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardManagementServiceServer).InsertCustomerShard(ctx, req.(*InsertCustomerShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardManagementService_LookupAccountShardPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAccountShardPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardManagementServiceServer).LookupAccountShardPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardManagementService_LookupAccountShardPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardManagementServiceServer).LookupAccountShardPair(ctx, req.(*LookupAccountShardPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardManagementService_LookupAccountShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAccountShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardManagementServiceServer).LookupAccountShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardManagementService_LookupAccountShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardManagementServiceServer).LookupAccountShard(ctx, req.(*LookupAccountShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShardManagementService_LookupCustomerShard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupCustomerShardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShardManagementServiceServer).LookupCustomerShard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShardManagementService_LookupCustomerShard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShardManagementServiceServer).LookupCustomerShard(ctx, req.(*LookupCustomerShardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShardManagementService_ServiceDesc is the grpc.ServiceDesc for ShardManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShardManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shardman.ShardManagementService",
	HandlerType: (*ShardManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertAccountShard",
			Handler:    _ShardManagementService_InsertAccountShard_Handler,
		},
		{
			MethodName: "InsertCustomerShard",
			Handler:    _ShardManagementService_InsertCustomerShard_Handler,
		},
		{
			MethodName: "LookupAccountShardPair",
			Handler:    _ShardManagementService_LookupAccountShardPair_Handler,
		},
		{
			MethodName: "LookupAccountShard",
			Handler:    _ShardManagementService_LookupAccountShard_Handler,
		},
		{
			MethodName: "LookupCustomerShard",
			Handler:    _ShardManagementService_LookupCustomerShard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "shardman/service_shardman.proto",
}
