# PersistentVolume (PV) defines the storage resource in the cluster
apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-service-pv
  labels:
    type: local
    app: auth-service
spec:
  storageClassName: manual # Storage class to use for this PV
  capacity:
    storage: 5Gi # Storage capacity for the PV
  accessModes:
    - ReadWriteMany # PV access mode (can be accessed by multiple pods)
  hostPath:
    path: /data/auth-service-log # Specify a path on the host machine

---
# PersistentVolumeClaim (PVC) allows a pod to request specific storage resources
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-pvc
  labels:
    app: auth-service
spec:
  storageClassName: manual # Storage class to use for this PVC
  accessModes:
    - ReadWriteMany # PVC access mode (matching the PV)
  resources:
    requests:
      storage: 5Gi # Requested storage for the PVC

---
# Deployment for the PostgreSQL instance
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1 # Number of pod replicas
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: tunvx/simple-bank-auth-service:v0.0.1 # Dockerhub container image
          ports:
            - containerPort: 8080 # Container port HTTP to expose
            - containerPort: 8090 # Container port GRPC to expose
          volumeMounts:
            - name: auth-service-log
              mountPath: /var/log # Log files volume mount
          command:
            [
              "/app/wait-for.sh",
              "redis:6379",
              "postgres02:5432",
              "--",
              "/app/start.sh",
            ]
          args: ["/app/main"] # Command to execute the main application
          resources:
            requests:
              cpu: "0.5" # Requested CPU for the container
              memory: "512Mi" # Requested memory for the container
            limits:
              cpu: "0.5" # Limit of CPU for the container
              memory: "512Mi" # Limit of memory for the container
      volumes:
        - name: auth-service-log
          persistentVolumeClaim:
            claimName: auth-service-pvc # Claim the PVC for the deployment
