apiVersion: v1
kind: Service
metadata:
  name: postgres01
spec:
  type: NodePort # Proper indentation
  selector:
    app: postgres01
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      # nodePort: 30432 # Must be within 30000-32767
