// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomerCredential(ctx context.Context, arg CreateCustomerCredentialParams) (CustomerCredential, error)
	CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) (CustomerSession, error)
	GetCustomerCredential(ctx context.Context, username string) (CustomerCredential, error)
	GetCustomerSession(ctx context.Context, sessionID uuid.UUID) (CustomerSession, error)
	UpdateCustomerCredential(ctx context.Context, arg UpdateCustomerCredentialParams) (CustomerCredential, error)
}

var _ Querier = (*Queries)(nil)
