// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: transactions/rpc_get_account_for_validate.proto

package transactions

import (
	account "github.com/tunvx/simplebank/grpc/pb/manage/account"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountForValidateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccNumber string `protobuf:"bytes,1,opt,name=acc_number,json=accNumber,proto3" json:"acc_number,omitempty"`
}

func (x *GetAccountForValidateRequest) Reset() {
	*x = GetAccountForValidateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_rpc_get_account_for_validate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountForValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountForValidateRequest) ProtoMessage() {}

func (x *GetAccountForValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_rpc_get_account_for_validate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountForValidateRequest.ProtoReflect.Descriptor instead.
func (*GetAccountForValidateRequest) Descriptor() ([]byte, []int) {
	return file_transactions_rpc_get_account_for_validate_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountForValidateRequest) GetAccNumber() string {
	if x != nil {
		return x.AccNumber
	}
	return ""
}

type GetAccountForValidateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account *account.Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *GetAccountForValidateResponse) Reset() {
	*x = GetAccountForValidateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_transactions_rpc_get_account_for_validate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountForValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountForValidateResponse) ProtoMessage() {}

func (x *GetAccountForValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transactions_rpc_get_account_for_validate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountForValidateResponse.ProtoReflect.Descriptor instead.
func (*GetAccountForValidateResponse) Descriptor() ([]byte, []int) {
	return file_transactions_rpc_get_account_for_validate_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountForValidateResponse) GetAccount() *account.Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_transactions_rpc_get_account_for_validate_proto protoreflect.FileDescriptor

var file_transactions_rpc_get_account_for_validate_proto_rawDesc = []byte{
	0x0a, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72,
	0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x66,
	0x6f, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x1c,
	0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x1d, 0x47,
	0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6f, 0x72, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x6e, 0x76, 0x78, 0x2f, 0x73, 0x69, 0x6d,
	0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_transactions_rpc_get_account_for_validate_proto_rawDescOnce sync.Once
	file_transactions_rpc_get_account_for_validate_proto_rawDescData = file_transactions_rpc_get_account_for_validate_proto_rawDesc
)

func file_transactions_rpc_get_account_for_validate_proto_rawDescGZIP() []byte {
	file_transactions_rpc_get_account_for_validate_proto_rawDescOnce.Do(func() {
		file_transactions_rpc_get_account_for_validate_proto_rawDescData = protoimpl.X.CompressGZIP(file_transactions_rpc_get_account_for_validate_proto_rawDescData)
	})
	return file_transactions_rpc_get_account_for_validate_proto_rawDescData
}

var file_transactions_rpc_get_account_for_validate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_transactions_rpc_get_account_for_validate_proto_goTypes = []any{
	(*GetAccountForValidateRequest)(nil),  // 0: transaction.GetAccountForValidateRequest
	(*GetAccountForValidateResponse)(nil), // 1: transaction.GetAccountForValidateResponse
	(*account.Account)(nil),               // 2: account.Account
}
var file_transactions_rpc_get_account_for_validate_proto_depIdxs = []int32{
	2, // 0: transaction.GetAccountForValidateResponse.account:type_name -> account.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transactions_rpc_get_account_for_validate_proto_init() }
func file_transactions_rpc_get_account_for_validate_proto_init() {
	if File_transactions_rpc_get_account_for_validate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_transactions_rpc_get_account_for_validate_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountForValidateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_transactions_rpc_get_account_for_validate_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetAccountForValidateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_transactions_rpc_get_account_for_validate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transactions_rpc_get_account_for_validate_proto_goTypes,
		DependencyIndexes: file_transactions_rpc_get_account_for_validate_proto_depIdxs,
		MessageInfos:      file_transactions_rpc_get_account_for_validate_proto_msgTypes,
	}.Build()
	File_transactions_rpc_get_account_for_validate_proto = out.File
	file_transactions_rpc_get_account_for_validate_proto_rawDesc = nil
	file_transactions_rpc_get_account_for_validate_proto_goTypes = nil
	file_transactions_rpc_get_account_for_validate_proto_depIdxs = nil
}
