// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: customer_session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomerSession = `-- name: CreateCustomerSession :one
INSERT INTO customer_sessions (
  session_id,
  customer_id,
  refresh_token,
  user_agent,
  client_ip,
  is_blocked,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING session_id, customer_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at
`

type CreateCustomerSessionParams struct {
	SessionID    uuid.UUID `json:"session_id"`
	CustomerID   int64     `json:"customer_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) CreateCustomerSession(ctx context.Context, arg CreateCustomerSessionParams) (CustomerSession, error) {
	row := q.db.QueryRow(ctx, createCustomerSession,
		arg.SessionID,
		arg.CustomerID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.IsBlocked,
		arg.ExpiresAt,
	)
	var i CustomerSession
	err := row.Scan(
		&i.SessionID,
		&i.CustomerID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerSession = `-- name: GetCustomerSession :one
SELECT session_id, customer_id, refresh_token, user_agent, client_ip, is_blocked, expires_at, created_at FROM customer_sessions
WHERE session_id = $1 LIMIT 1
`

func (q *Queries) GetCustomerSession(ctx context.Context, sessionID uuid.UUID) (CustomerSession, error) {
	row := q.db.QueryRow(ctx, getCustomerSession, sessionID)
	var i CustomerSession
	err := row.Scan(
		&i.SessionID,
		&i.CustomerID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.IsBlocked,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
