apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-service-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-service # Deployment name should auto-scale
  minReplicas: 1 # Minimum pod
  maxReplicas: 5 # Maximum pod
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Auto scale when CPU reachss 50% (testing) / 60% (product)
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60 # Auto scale when Memory reaches 60%/70% (product)
