global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080
      
  - job_name: node_exporter
    scrape_interval: 10s
    static_configs:
    - targets: 
      - node-exporter:9100
