// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: moneytransfer/rpc_receive_money.proto

package moneytransfer

import (
	account "github.com/tunvx/simplebank/grpc/pb/cusman/account"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Receiving transaction (Add money to account)
type ReceiveMoneyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount           int64  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrencyType     string `protobuf:"bytes,2,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
	BeneficiaryAccId int64  `protobuf:"varint,3,opt,name=beneficiary_acc_id,json=beneficiaryAccId,proto3" json:"beneficiary_acc_id,omitempty"` // Beneficiary account ID
	ReferenceNumber  string `protobuf:"bytes,4,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`       // Provided by the sending transaction
	Message          string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReceiveMoneyRequest) Reset() {
	*x = ReceiveMoneyRequest{}
	mi := &file_moneytransfer_rpc_receive_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMoneyRequest) ProtoMessage() {}

func (x *ReceiveMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneytransfer_rpc_receive_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMoneyRequest.ProtoReflect.Descriptor instead.
func (*ReceiveMoneyRequest) Descriptor() ([]byte, []int) {
	return file_moneytransfer_rpc_receive_money_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveMoneyRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReceiveMoneyRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

func (x *ReceiveMoneyRequest) GetBeneficiaryAccId() int64 {
	if x != nil {
		return x.BeneficiaryAccId
	}
	return 0
}

func (x *ReceiveMoneyRequest) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *ReceiveMoneyRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReceiveMoneyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccessed        bool             `protobuf:"varint,1,opt,name=is_successed,json=isSuccessed,proto3" json:"is_successed,omitempty"`
	Message            string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BeneficiaryAccount *account.Account `protobuf:"bytes,3,opt,name=beneficiary_account,json=beneficiaryAccount,proto3" json:"beneficiary_account,omitempty"` // Just for development phase
}

func (x *ReceiveMoneyResponse) Reset() {
	*x = ReceiveMoneyResponse{}
	mi := &file_moneytransfer_rpc_receive_money_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMoneyResponse) ProtoMessage() {}

func (x *ReceiveMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneytransfer_rpc_receive_money_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMoneyResponse.ProtoReflect.Descriptor instead.
func (*ReceiveMoneyResponse) Descriptor() ([]byte, []int) {
	return file_moneytransfer_rpc_receive_money_proto_rawDescGZIP(), []int{1}
}

func (x *ReceiveMoneyResponse) GetIsSuccessed() bool {
	if x != nil {
		return x.IsSuccessed
	}
	return false
}

func (x *ReceiveMoneyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReceiveMoneyResponse) GetBeneficiaryAccount() *account.Account {
	if x != nil {
		return x.BeneficiaryAccount
	}
	return nil
}

var File_moneytransfer_rpc_receive_money_proto protoreflect.FileDescriptor

var file_moneytransfer_rpc_receive_money_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x1a, 0x1c, 0x63, 0x75, 0x73, 0x6d, 0x61, 0x6e, 0x2f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc5, 0x01, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x62, 0x65, 0x6e,
	0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72, 0x79, 0x5f, 0x61, 0x63, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61,
	0x72, 0x79, 0x41, 0x63, 0x63, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x66, 0x65, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x96, 0x01, 0x0a,
	0x14, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x41, 0x0a, 0x13, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72,
	0x79, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x12, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72, 0x79, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x6e, 0x76, 0x78, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_moneytransfer_rpc_receive_money_proto_rawDescOnce sync.Once
	file_moneytransfer_rpc_receive_money_proto_rawDescData = file_moneytransfer_rpc_receive_money_proto_rawDesc
)

func file_moneytransfer_rpc_receive_money_proto_rawDescGZIP() []byte {
	file_moneytransfer_rpc_receive_money_proto_rawDescOnce.Do(func() {
		file_moneytransfer_rpc_receive_money_proto_rawDescData = protoimpl.X.CompressGZIP(file_moneytransfer_rpc_receive_money_proto_rawDescData)
	})
	return file_moneytransfer_rpc_receive_money_proto_rawDescData
}

var file_moneytransfer_rpc_receive_money_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moneytransfer_rpc_receive_money_proto_goTypes = []any{
	(*ReceiveMoneyRequest)(nil),  // 0: moneytransfer.ReceiveMoneyRequest
	(*ReceiveMoneyResponse)(nil), // 1: moneytransfer.ReceiveMoneyResponse
	(*account.Account)(nil),      // 2: account.Account
}
var file_moneytransfer_rpc_receive_money_proto_depIdxs = []int32{
	2, // 0: moneytransfer.ReceiveMoneyResponse.beneficiary_account:type_name -> account.Account
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_moneytransfer_rpc_receive_money_proto_init() }
func file_moneytransfer_rpc_receive_money_proto_init() {
	if File_moneytransfer_rpc_receive_money_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moneytransfer_rpc_receive_money_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moneytransfer_rpc_receive_money_proto_goTypes,
		DependencyIndexes: file_moneytransfer_rpc_receive_money_proto_depIdxs,
		MessageInfos:      file_moneytransfer_rpc_receive_money_proto_msgTypes,
	}.Build()
	File_moneytransfer_rpc_receive_money_proto = out.File
	file_moneytransfer_rpc_receive_money_proto_rawDesc = nil
	file_moneytransfer_rpc_receive_money_proto_goTypes = nil
	file_moneytransfer_rpc_receive_money_proto_depIdxs = nil
}
