// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: moneytransfer/rpc_check_account.proto

package moneytransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountNumber string `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CurrencyType  string `protobuf:"bytes,2,opt,name=currency_type,json=currencyType,proto3" json:"currency_type,omitempty"`
}

func (x *CheckAccountRequest) Reset() {
	*x = CheckAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moneytransfer_rpc_check_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountRequest) ProtoMessage() {}

func (x *CheckAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moneytransfer_rpc_check_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountRequest.ProtoReflect.Descriptor instead.
func (*CheckAccountRequest) Descriptor() ([]byte, []int) {
	return file_moneytransfer_rpc_check_account_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccountRequest) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *CheckAccountRequest) GetCurrencyType() string {
	if x != nil {
		return x.CurrencyType
	}
	return ""
}

type CheckAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsValid   bool   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	OwnerName string `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
}

func (x *CheckAccountResponse) Reset() {
	*x = CheckAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moneytransfer_rpc_check_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccountResponse) ProtoMessage() {}

func (x *CheckAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moneytransfer_rpc_check_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccountResponse.ProtoReflect.Descriptor instead.
func (*CheckAccountResponse) Descriptor() ([]byte, []int) {
	return file_moneytransfer_rpc_check_account_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccountResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *CheckAccountResponse) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

var File_moneytransfer_rpc_check_account_proto protoreflect.FileDescriptor

var file_moneytransfer_rpc_check_account_proto_rawDesc = []byte{
	0x0a, 0x25, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x2f,
	0x72, 0x70, 0x63, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x61, 0x0a, 0x13, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x54, 0x79, 0x70, 0x65, 0x22, 0x50, 0x0a, 0x14, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x75, 0x6e, 0x76, 0x78, 0x2f,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x62, 0x61, 0x6e, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moneytransfer_rpc_check_account_proto_rawDescOnce sync.Once
	file_moneytransfer_rpc_check_account_proto_rawDescData = file_moneytransfer_rpc_check_account_proto_rawDesc
)

func file_moneytransfer_rpc_check_account_proto_rawDescGZIP() []byte {
	file_moneytransfer_rpc_check_account_proto_rawDescOnce.Do(func() {
		file_moneytransfer_rpc_check_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_moneytransfer_rpc_check_account_proto_rawDescData)
	})
	return file_moneytransfer_rpc_check_account_proto_rawDescData
}

var file_moneytransfer_rpc_check_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moneytransfer_rpc_check_account_proto_goTypes = []any{
	(*CheckAccountRequest)(nil),  // 0: moneytransfer.CheckAccountRequest
	(*CheckAccountResponse)(nil), // 1: moneytransfer.CheckAccountResponse
}
var file_moneytransfer_rpc_check_account_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moneytransfer_rpc_check_account_proto_init() }
func file_moneytransfer_rpc_check_account_proto_init() {
	if File_moneytransfer_rpc_check_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moneytransfer_rpc_check_account_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*CheckAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moneytransfer_rpc_check_account_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CheckAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moneytransfer_rpc_check_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moneytransfer_rpc_check_account_proto_goTypes,
		DependencyIndexes: file_moneytransfer_rpc_check_account_proto_depIdxs,
		MessageInfos:      file_moneytransfer_rpc_check_account_proto_msgTypes,
	}.Build()
	File_moneytransfer_rpc_check_account_proto = out.File
	file_moneytransfer_rpc_check_account_proto_rawDesc = nil
	file_moneytransfer_rpc_check_account_proto_goTypes = nil
	file_moneytransfer_rpc_check_account_proto_depIdxs = nil
}
