// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: moneytransfer/service_moneytransfer.proto

package moneytransfer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoneyTransfer_CheckAccount_FullMethodName                          = "/moneytransfer.MoneyTransfer/CheckAccount"
	MoneyTransfer_ReceiveMoney_FullMethodName                          = "/moneytransfer.MoneyTransfer/ReceiveMoney"
	MoneyTransfer_InternalTransferMoney_FullMethodName                 = "/moneytransfer.MoneyTransfer/InternalTransferMoney"
	MoneyTransfer_ExternalTransferMoney_FullMethodName                 = "/moneytransfer.MoneyTransfer/ExternalTransferMoney"
	MoneyTransfer_TestEmptyGET_FullMethodName                          = "/moneytransfer.MoneyTransfer/TestEmptyGET"
	MoneyTransfer_TestEmptyPOST_FullMethodName                         = "/moneytransfer.MoneyTransfer/TestEmptyPOST"
	MoneyTransfer_TestCheckAccountNoProcessing_FullMethodName          = "/moneytransfer.MoneyTransfer/TestCheckAccountNoProcessing"
	MoneyTransfer_TestCheckAccountJustAuth_FullMethodName              = "/moneytransfer.MoneyTransfer/TestCheckAccountJustAuth"
	MoneyTransfer_TestInternalTransferMoneyNoProcessing_FullMethodName = "/moneytransfer.MoneyTransfer/TestInternalTransferMoneyNoProcessing"
	MoneyTransfer_TestInternalTransferMoneyJustAuth_FullMethodName     = "/moneytransfer.MoneyTransfer/TestInternalTransferMoneyJustAuth"
)

// MoneyTransferClient is the client API for MoneyTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoneyTransferClient interface {
	// Kiểm tra tài khoản
	CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error)
	// Nhận tiền (Receive Money)
	ReceiveMoney(ctx context.Context, in *ReceiveMoneyRequest, opts ...grpc.CallOption) (*ReceiveMoneyResponse, error)
	// Chuyển khoản nội bộ (Internal Transfer)
	InternalTransferMoney(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*InternalTransferMoneyResponse, error)
	// Chuyển khoản liên ngân hàng (External Transfer)
	ExternalTransferMoney(ctx context.Context, in *ExternalTransferMoneyRequest, opts ...grpc.CallOption) (*ExternalTransferMoneyResponse, error)
	TestEmptyGET(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OkayResponse, error)
	TestEmptyPOST(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OkayResponse, error)
	TestCheckAccountNoProcessing(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*OkayResponse, error)
	TestCheckAccountJustAuth(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*OkayResponse, error)
	TestInternalTransferMoneyNoProcessing(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*OkayResponse, error)
	TestInternalTransferMoneyJustAuth(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*OkayResponse, error)
}

type moneyTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewMoneyTransferClient(cc grpc.ClientConnInterface) MoneyTransferClient {
	return &moneyTransferClient{cc}
}

func (c *moneyTransferClient) CheckAccount(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*CheckAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccountResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_CheckAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) ReceiveMoney(ctx context.Context, in *ReceiveMoneyRequest, opts ...grpc.CallOption) (*ReceiveMoneyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveMoneyResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_ReceiveMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) InternalTransferMoney(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*InternalTransferMoneyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InternalTransferMoneyResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_InternalTransferMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) ExternalTransferMoney(ctx context.Context, in *ExternalTransferMoneyRequest, opts ...grpc.CallOption) (*ExternalTransferMoneyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalTransferMoneyResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_ExternalTransferMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestEmptyGET(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestEmptyGET_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestEmptyPOST(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestEmptyPOST_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestCheckAccountNoProcessing(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestCheckAccountNoProcessing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestCheckAccountJustAuth(ctx context.Context, in *CheckAccountRequest, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestCheckAccountJustAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestInternalTransferMoneyNoProcessing(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestInternalTransferMoneyNoProcessing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moneyTransferClient) TestInternalTransferMoneyJustAuth(ctx context.Context, in *InternalTransferMoneyRequest, opts ...grpc.CallOption) (*OkayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OkayResponse)
	err := c.cc.Invoke(ctx, MoneyTransfer_TestInternalTransferMoneyJustAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoneyTransferServer is the server API for MoneyTransfer service.
// All implementations must embed UnimplementedMoneyTransferServer
// for forward compatibility.
type MoneyTransferServer interface {
	// Kiểm tra tài khoản
	CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error)
	// Nhận tiền (Receive Money)
	ReceiveMoney(context.Context, *ReceiveMoneyRequest) (*ReceiveMoneyResponse, error)
	// Chuyển khoản nội bộ (Internal Transfer)
	InternalTransferMoney(context.Context, *InternalTransferMoneyRequest) (*InternalTransferMoneyResponse, error)
	// Chuyển khoản liên ngân hàng (External Transfer)
	ExternalTransferMoney(context.Context, *ExternalTransferMoneyRequest) (*ExternalTransferMoneyResponse, error)
	TestEmptyGET(context.Context, *Empty) (*OkayResponse, error)
	TestEmptyPOST(context.Context, *Empty) (*OkayResponse, error)
	TestCheckAccountNoProcessing(context.Context, *CheckAccountRequest) (*OkayResponse, error)
	TestCheckAccountJustAuth(context.Context, *CheckAccountRequest) (*OkayResponse, error)
	TestInternalTransferMoneyNoProcessing(context.Context, *InternalTransferMoneyRequest) (*OkayResponse, error)
	TestInternalTransferMoneyJustAuth(context.Context, *InternalTransferMoneyRequest) (*OkayResponse, error)
	mustEmbedUnimplementedMoneyTransferServer()
}

// UnimplementedMoneyTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoneyTransferServer struct{}

func (UnimplementedMoneyTransferServer) CheckAccount(context.Context, *CheckAccountRequest) (*CheckAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccount not implemented")
}
func (UnimplementedMoneyTransferServer) ReceiveMoney(context.Context, *ReceiveMoneyRequest) (*ReceiveMoneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveMoney not implemented")
}
func (UnimplementedMoneyTransferServer) InternalTransferMoney(context.Context, *InternalTransferMoneyRequest) (*InternalTransferMoneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalTransferMoney not implemented")
}
func (UnimplementedMoneyTransferServer) ExternalTransferMoney(context.Context, *ExternalTransferMoneyRequest) (*ExternalTransferMoneyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExternalTransferMoney not implemented")
}
func (UnimplementedMoneyTransferServer) TestEmptyGET(context.Context, *Empty) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestEmptyGET not implemented")
}
func (UnimplementedMoneyTransferServer) TestEmptyPOST(context.Context, *Empty) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestEmptyPOST not implemented")
}
func (UnimplementedMoneyTransferServer) TestCheckAccountNoProcessing(context.Context, *CheckAccountRequest) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestCheckAccountNoProcessing not implemented")
}
func (UnimplementedMoneyTransferServer) TestCheckAccountJustAuth(context.Context, *CheckAccountRequest) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestCheckAccountJustAuth not implemented")
}
func (UnimplementedMoneyTransferServer) TestInternalTransferMoneyNoProcessing(context.Context, *InternalTransferMoneyRequest) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestInternalTransferMoneyNoProcessing not implemented")
}
func (UnimplementedMoneyTransferServer) TestInternalTransferMoneyJustAuth(context.Context, *InternalTransferMoneyRequest) (*OkayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestInternalTransferMoneyJustAuth not implemented")
}
func (UnimplementedMoneyTransferServer) mustEmbedUnimplementedMoneyTransferServer() {}
func (UnimplementedMoneyTransferServer) testEmbeddedByValue()                       {}

// UnsafeMoneyTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoneyTransferServer will
// result in compilation errors.
type UnsafeMoneyTransferServer interface {
	mustEmbedUnimplementedMoneyTransferServer()
}

func RegisterMoneyTransferServer(s grpc.ServiceRegistrar, srv MoneyTransferServer) {
	// If the following call pancis, it indicates UnimplementedMoneyTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoneyTransfer_ServiceDesc, srv)
}

func _MoneyTransfer_CheckAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).CheckAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_CheckAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).CheckAccount(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_ReceiveMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).ReceiveMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_ReceiveMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).ReceiveMoney(ctx, req.(*ReceiveMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_InternalTransferMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransferMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).InternalTransferMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_InternalTransferMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).InternalTransferMoney(ctx, req.(*InternalTransferMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_ExternalTransferMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalTransferMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).ExternalTransferMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_ExternalTransferMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).ExternalTransferMoney(ctx, req.(*ExternalTransferMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestEmptyGET_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestEmptyGET(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestEmptyGET_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestEmptyGET(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestEmptyPOST_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestEmptyPOST(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestEmptyPOST_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestEmptyPOST(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestCheckAccountNoProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestCheckAccountNoProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestCheckAccountNoProcessing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestCheckAccountNoProcessing(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestCheckAccountJustAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestCheckAccountJustAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestCheckAccountJustAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestCheckAccountJustAuth(ctx, req.(*CheckAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestInternalTransferMoneyNoProcessing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransferMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestInternalTransferMoneyNoProcessing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestInternalTransferMoneyNoProcessing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestInternalTransferMoneyNoProcessing(ctx, req.(*InternalTransferMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MoneyTransfer_TestInternalTransferMoneyJustAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalTransferMoneyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoneyTransferServer).TestInternalTransferMoneyJustAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoneyTransfer_TestInternalTransferMoneyJustAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoneyTransferServer).TestInternalTransferMoneyJustAuth(ctx, req.(*InternalTransferMoneyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoneyTransfer_ServiceDesc is the grpc.ServiceDesc for MoneyTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoneyTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moneytransfer.MoneyTransfer",
	HandlerType: (*MoneyTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccount",
			Handler:    _MoneyTransfer_CheckAccount_Handler,
		},
		{
			MethodName: "ReceiveMoney",
			Handler:    _MoneyTransfer_ReceiveMoney_Handler,
		},
		{
			MethodName: "InternalTransferMoney",
			Handler:    _MoneyTransfer_InternalTransferMoney_Handler,
		},
		{
			MethodName: "ExternalTransferMoney",
			Handler:    _MoneyTransfer_ExternalTransferMoney_Handler,
		},
		{
			MethodName: "TestEmptyGET",
			Handler:    _MoneyTransfer_TestEmptyGET_Handler,
		},
		{
			MethodName: "TestEmptyPOST",
			Handler:    _MoneyTransfer_TestEmptyPOST_Handler,
		},
		{
			MethodName: "TestCheckAccountNoProcessing",
			Handler:    _MoneyTransfer_TestCheckAccountNoProcessing_Handler,
		},
		{
			MethodName: "TestCheckAccountJustAuth",
			Handler:    _MoneyTransfer_TestCheckAccountJustAuth_Handler,
		},
		{
			MethodName: "TestInternalTransferMoneyNoProcessing",
			Handler:    _MoneyTransfer_TestInternalTransferMoneyNoProcessing_Handler,
		},
		{
			MethodName: "TestInternalTransferMoneyJustAuth",
			Handler:    _MoneyTransfer_TestInternalTransferMoneyJustAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moneytransfer/service_moneytransfer.proto",
}
