name: CI - Build and Push Manage Service Image

on:
  push:
    branches:
      - main
    paths:
      - 'services/manage-service/**'
      - 'app.env'
      - 'domolo/dockerfiles/Dockerfile.0001.manage'

env:
  DOCKER_REPOSITORY: tunvx/simple-bank-manage-service
  # BASE_TAG: ${{ github.sha }}
  BASE_TAG: 0.0.1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone Code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU (for multi-platform builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and Push 
      - name: Build and push Manage Service
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:v${{ env.BASE_TAG }}
          platforms: linux/amd64,linux/arm64
          file: domolo/dockerfiles/Dockerfile.0001.manage

      # Step 5: Build and Push
      # - name: Build and push Manage Service
      #   run: |
      #     docker buildx create --use
      #     docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_REPOSITORY:v${{ env.BASE_TAG }} -f domolo/dockerfiles/Dockerfile.0001.manage . --push
