name: CI/CD - Build and Push Auth Service Image

on:
  push:
    branches:
      - main
    paths:
      - 'vnb-auth-service/**'
      - 'start.sh' # I use that for trigger all.
      - 'vnb-auth-service/Dockerfile'

env:
  DOCKER_REPOSITORY: tunvx/vnb-auth-service
  # BASE_TAG: ${{ github.sha }}
  BASE_TAG: 0.0.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Clone Code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU (for multi-platform builds)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 5: Build and Push 
      - name: Build and push Auth Service
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_REPOSITORY }}:v${{ env.BASE_TAG }}
          platforms: linux/amd64,linux/arm64
          file: vnb-auth-service/Dockerfile